CREATE TABLE users (
    id VARCHAR(100) PRIMARY KEY,
)

CREATE TABLE groups (
    id VARCHAR(100 PRIMARY KEY,)
)

CREATE TABLE garbage_count (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    group_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE
)
